### ISSUE TITLE
Fix travis installation of zmq

### ISSUE THREAD

**Issue by codepunkt** [gonsfx/dispo#3]
At the moment, CI checks on travis fail because there apparently is an issue with the npm installation of `zmq`.

Most likely zeromq is not installed on the virtual travisCI instance the tests are running in:
`Failed at the zmq@2.15.3 install script 'node-gyp rebuild'`

**Comment by Evalle** [comment]
Hey @gonsfx I can try to fix it. I will let you know about my progress in a day.

**Comment by codepunkt** [comment]
@Evalle i've decided to use the `zmq-prebuilt` module with prebuilt zeromq binaries to work around the problem. Complicated travis configuration like done in the `zmq` nodejs package would overcomplicate things a lot and might introduce new problems.

**Comment by Evalle** [comment]
Ok, good choice. Thanks for letting me know.

Best regards, Evgeny Shmarnev.

---
