### ISSUE TITLE
Send an email when a job failed

### ISSUE THREAD

**Issue by codepunkt** [gonsfx/dispo#8]
When a job fails after all available retries, send an email to selected recipients to inform them of the failure

Allow configuration of recipients in the configuration file on a per-job basis, but also allow to override it when queing jobs for single runs using ZMQ.

**Comment by kbariotis** [comment]
Hello there,

have you thought about how to send an email? Is it going to be an external service? If so, which one? I would love to help on this one.

**Comment by codepunkt** [comment]
@kbariotis Most likely using nodemailer with our without an external SMTP server (configurable)

**Comment by kbariotis** [comment]
Great! I will work on that!
